export default class Constant{
  // 登录标题大小
  static  readonly  LOGIN_SIZE:number=30
  // 登录标题颜色
  static  readonly  LOGIN_COLOR:string='#2F1155'
  // 输入框长度
  static readonly INPUT_WIDTH:number=300
  static readonly INPUT_HEIGHT:number=60
  static readonly BUTTON_WIDTH:number=150
  static readonly BUTTON_HEIGHT:number=50
  static readonly BUTTON_COLOR:string='#6E34BB'
  // 列表
  static readonly SPACE_SIZE:number=20
  static readonly OVERDUE_COLOR:string='#FFB1B0'
  static readonly FRESH_COLOR:string='#FFBB786'
  // 个人中心
  static readonly INPUT_IMAGE_SIZE:number=30
  static readonly AVATAR_SIZE:number=80

}
